services:
  frontend:
    build: ./frontend/
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./frontend/
          target: /app
          action: sync
  web:
    build:
      context: .
      target: final 
    ports:
      - 8000:8000
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
    develop:
      watch:
        - path: .
          target: /app
          action: sync+restart
  db:
    container_name: postgres 
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
