version: '3.8'

services:
  frontend:
    build: ./frontend/
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./frontend/
          target: /app
          action: sync
  web:
    build:
      context: .
      target: dev 
    ports:
      - 8000:8000
    environment:
      PRISMA_DB: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
    depends_on:
      - db
    develop:
      watch:
        - path: .
          target: /app
          action: sync+restart
  db:
    container_name: postgres 
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
