services:
  frontend:
    build: ./frontend/
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./frontend/
          target: /app
          action: sync
  web:
    build:
      context: .
      target: dev 
    ports:
      - 8000:8000
    environment:
      DB_URL: "./frontend/prisma/dev.db"
    volumes:
      - db-data:/app/frontend/prisma
    develop:
      watch:
        - path: .
          target: /app
          action: sync+restart
volumes:
  db-data:
