services:
  web:
    build:
      context: .
      target: dev
    ports:
      - 8000:8000
    restart: always
    develop:
      watch:
        - path: .
          target: /app
          action: sync+restart
          ignore:
            - /frontend
        - path: ./frontend/
          target: /app/frontend
          action: sync
